DPortal/Models/Employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string JobDesc { get; set; }
        public string Number { get; set; }
        public string Department { get; set; }
        public decimal HourlyPay { get; set; }
        public decimal Bonus { get; set; }
        public int EmployeeTypeId { get; set; }
        public Nullable<decimal> HouseAllowance { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public string ComputerDetails { get; set; }
        public string SystemConfigurationDetails { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}

DPortal/Models/EmployeeType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeType()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public string Types { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}

DPortal/Controllers/EmployeesController.cs
//using DPortal.Factory;
using DPortal.Builder.ConcreteBuilder;
using DPortal.Builder.IBuilder;
using DPortal.Factory.AbstractFactory;
using DPortal.Factory.FactoryMethod;
using DPortal.Models;
using System;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Director = DPortal.Builder.Director;

namespace DPortal.Controllers
{
    public class EmployeesController : BaseController
    {
        private EmployeePortalEntities db = new EmployeePortalEntities();

        // GET: Employees
        public ActionResult Index()
        {
            var employees = db.Employees.Include(e => e.EmployeeType);
            return View(employees.ToList());
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeTypeId = new SelectList(db.EmployeeTypes, "Id", "Types");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,JobDesc,Number,Department,HourlyPay,Bonus,EmployeeTypeId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                //EmployeeManagerFactory empFactory = new EmployeeManagerFactory();
                //IEmployeeManager empManager = empFactory.GetEmployeeManager(employee.EmployeeTypeId);
                //if (empManager != null)
                //{
                //    employee.Bonus = empManager.GetBonus();
                //    employee.HourlyPay = empManager.GetHourlyPay();
                //}

                BaseEmployeeFactory employeeFactory = new EmployeeManagerFactory().CreateFactory(employee);
                employeeFactory.ApplySalary();

                IComputerFactory computerFactory = new EmployeeSystemFactory().Create(employee);
                EmployeeSystemManager manager = new EmployeeSystemManager(computerFactory);
                employee.ComputerDetails = manager.GetSystemDetails();

                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeTypeId = new SelectList(db.EmployeeTypes, "Id", "Types", employee.EmployeeTypeId);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeTypeId = new SelectList(db.EmployeeTypes, "Id", "Types", employee.EmployeeTypeId);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,JobDesc,Number,Department,HourlyPay,Bonus,EmployeeTypeId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeTypeId = new SelectList(db.EmployeeTypes, "Id", "Types", employee.EmployeeTypeId);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult BuildSystem(int? Id)
        {
            //return View(Id);
            Employee employee = db.Employees.Find(Id);
            if (employee.ComputerDetails.Contains("Laptop"))
            {
                return View("BuildLaptop", Id);
            }
            else
            {
                return View("BuildDesktop", Id);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BuildLaptop(FormCollection collection)
        {
            Employee employee = db.Employees.Find(Convert.ToInt32(collection["Id"]));
            ISystemBuilder systemBuilder = new LaptopBuilder();

            Director.ConfigurationBuilder configurationBuilder = new Director.ConfigurationBuilder();
            configurationBuilder.BuildSystem(systemBuilder, collection);
            ComputerSystem computerSystem = systemBuilder.GetSystem();

            employee.SystemConfigurationDetails = string.Format("RAM: {0},HDDSize: {1},TouchScreen: {2}", computerSystem.RAM,
                computerSystem.HDDSize, computerSystem.TouchScreen);

            db.Entry(employee).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BuildDesktop(FormCollection collection)
        {
            Employee employee = db.Employees.Find(Convert.ToInt32(collection["Id"]));
            ISystemBuilder systemBuilder = new DesktopBuilder();

            Director.ConfigurationBuilder configurationBuilder = new Director.ConfigurationBuilder();
            configurationBuilder.BuildSystem(systemBuilder, collection);
            ComputerSystem computerSystem = systemBuilder.GetSystem();

            employee.SystemConfigurationDetails = string.Format("RAM: {0},HDDSize: {1},Keyboard: {2},Mouse: {3}", computerSystem.RAM,
                computerSystem.HDDSize, computerSystem.Keyboard, computerSystem.Mouse );

            db.Entry(employee).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //[HttpPost]
        //public ActionResult BuildSystem(int Id, string RAM, string HDD)
        //{
        //    Employee employee = db.Employees.Find(Id);
        //    ComputerSystem computerSystem = new ComputerSystem(RAM, HDD);
        //    employee.SystemConfigurationDetails = computerSystem.Build();
        //    db.Entry(employee).State = EntityState.Modified;
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DPortal/Views/Employees/BuildDesktop.cshtml
@model Int32
@{
    ViewBag.Title = "BuildDesktop";
}

<h2>BuildDesktop</h2>


@using (Html.BeginForm("BuildDesktop", "Employees", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>System Configuration</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @Class = "text-danger" })
        @Html.Hidden("Id", this.Model)

        <div class="form-group">
            @Html.Label("Memory", htmlAttributes: new { @Class = "control-label" })
            <div class="col-md-10">
                @Html.DropDownList("RAM",new List<SelectListItem>() {
               new SelectListItem(){ Text = "Select" , Value = "Select"},
               new SelectListItem(){ Text = "8GB" , Value = "8GB"},
               new SelectListItem(){ Text = "16GB" , Value = "16GB"},
               new SelectListItem(){ Text = "32GB" , Value = "32GB"},
               new SelectListItem(){ Text = "64GB" , Value = "64GB"}
           }, htmlAttributes: new {@class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Drive", htmlAttributes: new { @Class = "control-label" })
            <div class="col-md-10">
                @Html.DropDownList("HDD",new List<SelectListItem>() {
               new SelectListItem(){ Text = "Select" , Value = "Select"},
               new SelectListItem(){ Text = "500GB" , Value = "500GB"},
               new SelectListItem(){ Text = "1TB" , Value = "1TB"},
               new SelectListItem(){ Text = "2TB" , Value = "2TB"},
               new SelectListItem(){ Text = "4TB" , Value = "4TB"}
           }, htmlAttributes: new {@class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Keyboard", htmlAttributes: new { @Class = "control-label" })
            <div class="col-md-10">
                @Html.DropDownList("Keyboard", new List<SelectListItem>() {
               new SelectListItem(){ Text = "Select" , Value = "Select"},
               new SelectListItem(){ Text = "Wireless" , Value = "Wireless"},
               new SelectListItem(){ Text = "USB" , Value = "USB"}
           }, htmlAttributes: new {@class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mouse", htmlAttributes: new { @Class = "control-label" })
            <div class="col-md-10">
                @Html.DropDownList("Mouse",new List<SelectListItem>() {
               new SelectListItem(){ Text = "Select" , Value = "Select"},
               new SelectListItem(){ Text = "Wireless" , Value = "Wireless"},
               new SelectListItem(){ Text = "USB" , Value = "USB"}
           }, htmlAttributes: new {@class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Employees")
</div>

DPortal/Views/Employees/BuildLaptop.cshtml
@model Int32
@{
    ViewBag.Title = "BuildLaptop";
}

<h2>BuildLaptop</h2>
<style>
    input[type=radio] {
        border: 0px;
        width: 100%;
        height: 1em;
    }
</style>

@using (Html.BeginForm("BuildLaptop", "Employees", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>System Configuration</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @Class = "text-danger" })
        @Html.Hidden("Id", this.Model)

        <div class="form-group">
            @Html.Label("Memory", htmlAttributes: new { @Class = "control-label" })
            <div class="col-md-10">
                @Html.DropDownList("RAM",new List<SelectListItem>() {
               new SelectListItem(){ Text = "Select" , Value = "Select"},
               new SelectListItem(){ Text = "8GB" , Value = "8GB"},
               new SelectListItem(){ Text = "16GB" , Value = "16GB"},
               new SelectListItem(){ Text = "32GB" , Value = "32GB"},
               new SelectListItem(){ Text = "64GB" , Value = "64GB"}
           }, htmlAttributes: new {@class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Drive", htmlAttributes: new { @Class = "control-label" })
            <div class="col-md-10">
                @Html.DropDownList("HDD",new List<SelectListItem>() {
               new SelectListItem(){ Text = "Select" , Value = "Select"},
               new SelectListItem(){ Text = "500GB" , Value = "500GB"},
               new SelectListItem(){ Text = "1TB" , Value = "1TB"},
               new SelectListItem(){ Text = "2TB" , Value = "2TB"},
               new SelectListItem(){ Text = "4TB" , Value = "4TB"}
           }, htmlAttributes: new {@class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Touch Enabled", htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                <div class="col-md-1">
                    <label>@Html.RadioButton("TouchScreen", "Yes", false, htmlAttributes: new { })
                    </label>
                    Yes
                </div>
                <div class="col-md-1">
                    <label>@Html.RadioButton("TouchScreen", "No", false, htmlAttributes: new { })</label>
                    No
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
}

    <div>
        @Html.ActionLink("Back to List", "Index", "Employees")
    </div>

DPortal/Views/Employees/BuildSystem.cshtml
@model Int32

    @using (Html.BeginForm("BuildSystem", "Employees", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>System Configuration</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @Class = "text-danger" })
            @Html.Hidden("Id", this.Model)
            
            <div class="form-group">
                @Html.Label("Memory", htmlAttributes: new { @Class = "control-label" })
                <div class="col-md-10">
                    @Html.DropDownList("RAM",new List<SelectListItem>() {
                   new SelectListItem(){ Text = "Select" , Value = "Select"},
                   new SelectListItem(){ Text = "8GB" , Value = "8GB"},
                   new SelectListItem(){ Text = "16GB" , Value = "16GB"},
                   new SelectListItem(){ Text = "32GB" , Value = "32GB"},
                   new SelectListItem(){ Text = "64GB" , Value = "64GB"}
               }, htmlAttributes: new {@class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Drive", htmlAttributes: new { @Class = "control-label" })
                <div class="col-md-10">
                    @Html.DropDownList("HDD",new List<SelectListItem>() {
                   new SelectListItem(){ Text = "Select" , Value = "Select"},
                   new SelectListItem(){ Text = "500GB" , Value = "500GB"},
                   new SelectListItem(){ Text = "1TB" , Value = "1TB"},
                   new SelectListItem(){ Text = "2TB" , Value = "2TB"},
                   new SelectListItem(){ Text = "4TB" , Value = "4TB"}
               }, htmlAttributes: new {@class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>

        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "", "Index")
    </div>

DPortal/Views/Employees/Create.cshtml
@model DPortal.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.HourlyPay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HourlyPay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HourlyPay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bonus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bonus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bonus, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeTypeId, "EmployeeTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DPortal/Views/Employees/Delete.cshtml
@model DPortal.Models.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HourlyPay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HourlyPay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bonus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeType.Types)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeType.Types)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DPortal/Views/Employees/Details.cshtml
@model DPortal.Models.Employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HourlyPay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HourlyPay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bonus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeType.Types)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeType.Types)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DPortal/Views/Employees/Edit.cshtml
@model DPortal.Models.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HourlyPay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HourlyPay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HourlyPay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bonus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bonus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bonus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeTypeId, "EmployeeTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}